import PDFDocument from "pdfkit";

export const config = {
  api: { bodyParser: { sizeLimit: "6mb" } },
  maxDuration: 30
};

const ACCENT = "#16a34a";
const TEXT = "#1c1917";
const MUTED = "#78716c";
const LIGHT = "#f5f2ee";

function drawLine(doc, y, color="#d4cbbf", width=0.5) {
  doc.moveTo(50, y).lineTo(doc.page.width - 50, y)
     .strokeColor(color).lineWidth(width).stroke();
}

function addFooter(doc) {
  const y = doc.page.height - 36;
  drawLine(doc, y, "#e8e0d5", 0.5);
  doc.fontSize(7.5).font("Helvetica").fillColor("#a8a29e")
     .text("Generated by ATSCheckPro  ·  resume-optimizer-brown.vercel.app  ·  Confidential", 50, y + 6, { align: "center", width: doc.page.width - 100 });
}

function buildResumePDF(doc, optimizedText, photo) {
  const lines = (optimizedText || "").split("\n");
  const name = lines[0]?.trim() || "";

  // Collect all contact lines (lines 1-3 that look like contact info)
  let contactLines = [];
  let bodyStart = 1;
  for (let i = 1; i < Math.min(5, lines.length); i++) {
    const l = lines[i].trim();
    if (!l) { bodyStart = i + 1; break; }
    // If line looks like contact info (has @, |, +, phone pattern, or URL)
    if (l.includes("@") || l.includes("|") || l.includes("+") || l.match(/\d{3}/) || l.includes("linkedin") || l.includes("github") || l.includes("http")) {
      contactLines.push(l);
      bodyStart = i + 1;
    } else {
      bodyStart = i;
      break;
    }
  }
  const body = lines.slice(bodyStart);

  // HEADER SECTION
  const headerY = 45;

  // Photo (right side)
  if (photo) {
    try {
      const imgData = photo.replace(/^data:image\/\w+;base64,/, "");
      doc.image(Buffer.from(imgData, "base64"), doc.page.width - 120, headerY, { width: 68, height: 68, align: "center" });
    } catch(e) {}
  }

  // Name
  doc.fontSize(22).font("Helvetica-Bold").fillColor(TEXT).text(name, 50, headerY, { width: doc.page.width - (photo ? 180 : 110) });

  // Contact details - each on separate line with icons
  let cy = headerY + 30;
  if (contactLines.length > 0) {
    // Split contact by | if all on one line
    let allContacts = [];
    for (const cl of contactLines) {
      if (cl.includes("|")) {
        allContacts.push(...cl.split("|").map(c => c.trim()).filter(Boolean));
      } else {
        allContacts.push(cl);
      }
    }
    // Show up to 4 contact items
    doc.fontSize(9).font("Helvetica").fillColor(MUTED);
    const contactStr = allContacts.slice(0, 4).join("   |   ");
    doc.text(contactStr, 50, cy, { width: doc.page.width - (photo ? 180 : 110), lineGap: 3 });
    cy = doc.y + 4;
  }

  // Accent line under header
  cy = Math.max(cy, headerY + 58);
  doc.moveTo(50, cy).lineTo(doc.page.width - 50, cy).strokeColor(ACCENT).lineWidth(2).stroke();
  doc.y = cy + 10;

  // BODY
  for (const line of body) {
    const t = line.trim();
    if (!t) { doc.moveDown(0.25); continue; }

    // Section header (ALL CAPS)
    if (t === t.toUpperCase() && t.length > 2 && t.length < 50 && !/^\d/.test(t) && /[A-Z]/.test(t)) {
      doc.moveDown(0.5);
      // Section header background
      const secY = doc.y;
      doc.rect(50, secY, doc.page.width - 100, 14).fill("#f0fdf4");
      doc.fontSize(8).font("Helvetica-Bold").fillColor(ACCENT)
         .text(t, 54, secY + 3, { characterSpacing: 1.5 });
      doc.y = secY + 18;
      doc.moveDown(0.2);
      continue;
    }

    // Bullet
    if (t.startsWith("-") || t.startsWith("•")) {
      const txt = t.replace(/^[-•]\s*/, "");
      const bY = doc.y;
      doc.fontSize(9).font("Helvetica").fillColor(ACCENT).text("▸", 50, bY);
      doc.fontSize(9.5).font("Helvetica").fillColor(TEXT)
         .text(txt, 64, bY, { width: doc.page.width - 114, lineGap: 2 });
      doc.moveDown(0.15);
      continue;
    }

    // Job title / company (has - or |)
    if ((t.includes(" - ") || t.includes(" | ")) && t.length < 100 && !t.includes("@")) {
      doc.moveDown(0.25);
      const parts = t.split(/\s[-|]\s/);
      doc.fontSize(10.5).font("Helvetica-Bold").fillColor(TEXT).text(parts[0] || t, { continued: parts.length > 1 });
      if (parts.length > 1) {
        doc.fontSize(9.5).font("Helvetica").fillColor(MUTED).text("  —  " + parts.slice(1).join(" — "));
      }
      doc.moveDown(0.15);
      continue;
    }

    // Regular
    doc.fontSize(9.5).font("Helvetica").fillColor(TEXT).text(t, { lineGap: 1.5 });
    doc.moveDown(0.1);
  }

  addFooter(doc);
}

function buildCoverPDF(doc, coverLetter) {
  const pageW = doc.page.width;
  const margin = 70;
  const contentW = pageW - margin * 2;

  // TOP ACCENT BAR
  doc.rect(0, 0, pageW, 6).fill(ACCENT);

  // Company/letterhead area
  doc.fontSize(10).font("Helvetica-Bold").fillColor(ACCENT)
     .text("ATSCheckPro", margin, 30, { align: "left" });
  doc.fontSize(8).font("Helvetica").fillColor(MUTED)
     .text("AI-Powered Resume & Cover Letter Service", margin, 44);

  drawLine(doc, 58, "#d4cbbf", 0.5);

  // Date - right aligned
  const today = new Date().toLocaleDateString("en-US", { year:"numeric", month:"long", day:"numeric" });
  doc.fontSize(9.5).font("Helvetica").fillColor(MUTED)
     .text(today, margin, 72, { width: contentW, align: "right" });

  doc.y = 100;

  // Parse cover letter into sections
  const rawText = (coverLetter || "").trim();
  const paragraphs = rawText.split(/\n\n+/).filter(p => p.trim());

  for (let i = 0; i < paragraphs.length; i++) {
    const para = paragraphs[i].trim().replace(/\n/g, " ");

    // Salutation (Dear...)
    if (para.startsWith("Dear") || para.startsWith("To ")) {
      doc.fontSize(10.5).font("Helvetica-Bold").fillColor(TEXT)
         .text(para, margin, doc.y, { width: contentW, align: "left" });
      doc.moveDown(0.8);
      continue;
    }

    // Closing (Sincerely, Best regards etc)
    if (para.match(/^(Sincerely|Best regards|Warm regards|Respectfully|Thank you|Yours)/i)) {
      doc.moveDown(0.5);
      doc.fontSize(10.5).font("Helvetica").fillColor(TEXT)
         .text(para, margin, doc.y, { width: contentW, align: "left" });
      doc.moveDown(2);
      // Signature line
      doc.moveTo(margin, doc.y).lineTo(margin + 180, doc.y)
         .strokeColor("#d4cbbf").lineWidth(0.8).stroke();
      doc.fontSize(8.5).font("Helvetica").fillColor(MUTED)
         .text("Signature", margin, doc.y + 4);
      continue;
    }

    // Body paragraphs - justified
    doc.fontSize(10.5).font("Helvetica").fillColor(TEXT)
       .text(para, margin, doc.y, { width: contentW, align: "justify", lineGap: 3 });
    doc.moveDown(0.8);
  }

  addFooter(doc);
}

function buildReportPDF(doc, report) {
  const score = report?.score || 0;
  const scoreAfter = report?.scoreAfter || Math.min(score + 8, 95);
  const improvement = scoreAfter - score;
  const pageW = doc.page.width;

  // TOP ACCENT BAR
  doc.rect(0, 0, pageW, 6).fill(ACCENT);

  // Header
  doc.fontSize(22).font("Helvetica-Bold").fillColor(TEXT).text("ATS Resume Report", 50, 30);
  doc.fontSize(9).font("Helvetica").fillColor(MUTED)
     .text("Powered by ATSCheckPro · " + new Date().toLocaleDateString("en-US", {year:"numeric",month:"long",day:"numeric"}), 50, 58);
  drawLine(doc, 74, ACCENT, 1.5);
  doc.y = 88;

  // SCORE BOXES
  const boxW = (pageW - 120) / 3;
  const boxes = [
    { label: "BEFORE", value: score + "/100", color: score >= 75 ? ACCENT : score >= 60 ? "#d97706" : "#dc2626", bg: "#fef9f0" },
    { label: "AFTER", value: scoreAfter + "/100", color: ACCENT, bg: "#f0fdf4" },
    { label: "IMPROVEMENT", value: "+" + improvement + " pts", color: "#1d4ed8", bg: "#eff6ff" }
  ];
  boxes.forEach((b, i) => {
    const x = 50 + i * (boxW + 10);
    const y = doc.y;
    doc.rect(x, y, boxW, 54).fill(b.bg).stroke("#e8e0d5");
    doc.fontSize(7).font("Helvetica-Bold").fillColor(MUTED).text(b.label, x, y + 8, { width: boxW, align: "center", characterSpacing: 1 });
    doc.fontSize(18).font("Helvetica-Bold").fillColor(b.color).text(b.value, x, y + 20, { width: boxW, align: "center" });
  });
  doc.y += 64;

  // STRENGTH
  const strength = score >= 75 ? "Strong Match" : score >= 60 ? "Moderate Match" : "Needs Improvement";
  doc.fontSize(9).font("Helvetica").fillColor(MUTED).text("Overall Assessment: ", { continued: true });
  doc.font("Helvetica-Bold").fillColor(score >= 75 ? ACCENT : score >= 60 ? "#d97706" : "#dc2626").text(strength);
  doc.moveDown(1.2);

  // SECTION helper
  function section(title) {
    doc.moveDown(0.3);
    const sy = doc.y;
    doc.rect(50, sy, pageW - 100, 16).fill("#f0fdf4");
    doc.fontSize(8).font("Helvetica-Bold").fillColor(ACCENT)
       .text(title, 54, sy + 4, { characterSpacing: 1 });
    doc.y = sy + 20;
    doc.moveDown(0.2);
  }

  // RECRUITER IMPRESSION
  if (report?.impression?.length) {
    section("RECRUITER IMPRESSION");
    for (const item of report.impression) {
      doc.fontSize(10).font("Helvetica").fillColor(TEXT)
         .text("→  " + item, 54, doc.y, { width: pageW - 110, lineGap: 2 });
      doc.moveDown(0.3);
    }
  }

  // MISSING KEYWORDS
  if (report?.keywords?.length) {
    section("MISSING KEYWORDS — ADD THESE TO YOUR RESUME");
    doc.fontSize(9.5).font("Helvetica").fillColor("#991b1b")
       .text(report.keywords.join("   ·   "), 54, doc.y, { width: pageW - 110, lineGap: 3 });
    doc.moveDown(0.5);
  }

  // IMPROVEMENT NOTES
  if (report?.notes?.length) {
    section("IMPROVEMENT NOTES");
    for (const note of report.notes) {
      const ny = doc.y;
      doc.rect(50, ny, 3, 12).fill(ACCENT);
      doc.fontSize(10).font("Helvetica").fillColor(TEXT)
         .text(note, 60, ny, { width: pageW - 114, lineGap: 2 });
      doc.moveDown(0.4);
    }
  }

  addFooter(doc);
}

export default async function handler(req, res) {
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });
  try {
    const { type, optimizedText, coverLetter, report, photo } = req.body;
    const doc = new PDFDocument({ margin: 50, size: "A4", bufferPages: true });
    const chunks = [];
    doc.on("data", chunk => chunks.push(chunk));
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="ATSCheckPro-${type}.pdf"`);
    if (type === "resume") buildResumePDF(doc, optimizedText, photo);
    else if (type === "cover") buildCoverPDF(doc, coverLetter);
    else if (type === "report") buildReportPDF(doc, report);
    doc.end();
    await new Promise(resolve => doc.on("end", resolve));
    const buffer = Buffer.concat(chunks);
    res.setHeader("Content-Length", buffer.length);
    res.send(buffer);
  } catch(e) {
    console.error("Download error:", e);
    res.status(500).json({ error: e.message });
  }
}
