import PDFDocument from "pdfkit";

export const config = {
  api: { bodyParser: true },
  maxDuration: 30
};

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).end();

  const { optimizedText, licenseKey } = req.body || {};

  if (!optimizedText || !licenseKey) {
    return res.status(400).json({ error: 'Missing data.' });
  }

  try {
    const doc = new PDFDocument({
      size: 'LETTER',
      margins: { top: 50, bottom: 50, left: 60, right: 60 }
    });

    const chunks = [];
    doc.on('data', chunk => chunks.push(chunk));

    const lines = optimizedText.split('\n');
    let isFirstLine = true;
    let isSecondLine = false;

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i].trim();

      if (!line) { doc.moveDown(0.3); continue; }

      if (isFirstLine) {
        doc.fontSize(22).font('Helvetica-Bold').fillColor('#1a202c').text(line, { align: 'center' });
        doc.moveDown(0.2);
        isFirstLine = false;
        isSecondLine = true;
        continue;
      }

      if (isSecondLine) {
        doc.fontSize(10).font('Helvetica').fillColor('#4a5568').text(line, { align: 'center' });
        doc.moveDown(0.5);
        doc.moveTo(60, doc.y).lineTo(doc.page.width - 60, doc.y).strokeColor('#667eea').lineWidth(1.5).stroke();
        doc.moveDown(0.5);
        isSecondLine = false;
        continue;
      }

      const isHeader = (line === line.toUpperCase() && line.length > 2 && line.length < 50 && !line.includes('@') && !/^\d/.test(line));

      if (isHeader) {
        doc.moveDown(0.5);
        doc.fontSize(11).font('Helvetica-Bold').fillColor('#667eea').text(line);
        doc.moveTo(60, doc.y + 2).lineTo(doc.page.width - 60, doc.y + 2).strokeColor('#667eea').lineWidth(0.5).stroke();
        doc.moveDown(0.3);
        continue;
      }

      if (line.startsWith('-') || line.startsWith('•') || line.startsWith('*')) {
        const bulletText = line.replace(/^[-•*]\s*/, '');
        doc.fontSize(10).font('Helvetica').fillColor('#2d3748').text('•  ' + bulletText, { indent: 15, align: 'left', lineGap: 2 });
        doc.moveDown(0.1);
        continue;
      }

      const isSubHeader = ((line.includes(' - ') || line.includes(' | ')) && line.length < 100 && i > 1);

      if (isSubHeader) {
        doc.moveDown(0.3);
        doc.fontSize(10.5).font('Helvetica-Bold').fillColor('#2d3748').text(line);
        doc.moveDown(0.1);
        continue;
      }

      doc.fontSize(10).font('Helvetica').fillColor('#2d3748').text(line, { lineGap: 2 });
      doc.moveDown(0.1);
    }

    doc.fontSize(8).font('Helvetica').fillColor('#a0aec0')
       .text('Generated by ResumeMatch AI — resume-optimizer-brown.vercel.app', 60, doc.page.height - 40, { align: 'center', width: doc.page.width - 120 });

    doc.end();
    await new Promise(resolve => doc.on('end', resolve));
    const pdfBuffer = Buffer.concat(chunks);

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename="optimized-resume.pdf"');
    res.setHeader('Content-Length', pdfBuffer.length);
    res.send(pdfBuffer);

  } catch (err) {
    console.error("generate-pdf error:", err);
    return res.status(500).json({ error: "Failed to generate PDF: " + err.message });
  }
}